### ISSUE TITLE
Feature: Reimport photos

### ISSUE THREAD

**Issue by jazzsequence** [jtsternberg/DsgnWrks-Instagram-Importer#32]
In the case where you navigated away from the page and the query stopped before it could import all your pics, add a reimport button to force a reimport of pics.

Should include handling for posts that would match existing posts to prevent duplicates.

**Comment by jtsternberg** [comment]
In order to accommodate this feature, I needed to add a feature to blacklist photos from being re-imported if they were deleted before. With [this update](https://github.com/jtsternberg/DsgnWrks-Instagram-Importer/commit/7515c35fbb4aacf4a2ab7ae603aa6102b74063c0), that is now in place, so it should be more feasible to allow re-importing.

> Should include handling for posts that would match existing posts to prevent duplicates.

That's actually already built-in.

**Comment by jtsternberg** [comment]
New button:
![](http://b.ustin.co/kHbI+)
